replicaCount: 1

image:
  repository: utopiandrmer/comp-minio
  tag: latest

service:
  type: ClusterIP
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  protocol: TCP

env:
  activeProfile: dev
  timezone: Asia/Seoul

pv:
  capacity: 5Gi
  node:
    - "node2.comp"

secret:
  rootPasswordSecretName: comp_secret
  rootPasswordSecretKey: MINIO_ROOT_PASSWORD
