replicaCount: 1

image:
  repository: quay.io/minio/minio
  tag: latest

service:
  clusterIp:
    type: ClusterIP
    ports:
      - name: api
        protocol: TCP
        port: 9000
        targetPort: 9000
      - name: console
        protocol: TCP
        port: 9001
        targetPort: 9001

  loadBalance:
    type: LoadBalance
    ports:
      - name: console
        protocol: TCP
        port: 9001
        targetPort: 9001
    externalIps:
      - "192.168.56.40"


env:
  activeProfile: dev
  timezone: Asia/Seoul

pv:
  capacity: 5Gi
  node:
    - "node2.comp"

secret:
  rootPasswordSecretName: comp-secret
  rootPasswordSecretKey: MINIO_ROOT_PASSWORD
