apiVersion: gateway.networking.k8s.io/v1beta1  # 버전을 v1beta1로 변경해 보세요
kind: Gateway
metadata:
  name: comppi-gateway
  namespace: comppi-gateway
spec:
  gatewayClassName: comppi-nginx-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https-api
      port: 443
      protocol: HTTPS
      hostname: "api.comppi.site"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: api-tls
    - name: https-bucket
      port: 443
      protocol: HTTPS
      hostname: "bucket.comppi.site"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: bucket-tls
