apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: comppi-gateway
  namespace: comppi-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https-api
      port: 443
      protocol: HTTPS
      hostname: "api.comppi.site"
      allowedRoutes:
        namespaces:
          selector:
            matchLabels:
              environment: dev
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: api-tls
    - name: https-bucket
      port: 443
      protocol: HTTPS
      hostname: "bucket.com-p.site"
      allowedRoutes:
        namespaces:
          selector:
            matchLabels:
              environment: dev
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: bucket-tls
