apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: dev-route
  namespace: comppi-dev
spec:
  parentRefs:
    - name: comppi-gateway
      namespcae: comppi-gateway
  hostnames:
    - "dev.comppi.site"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: api-gateway
          port: 8000

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: api-route
  namespace: comppi-dev
spec:
  parentRefs:
    - name: comppi-gateway
  hostnames:
    - "api.comppi.site"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: api-gateway
          port: 8000

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: bucket-route
  namespace: comppi-dev
spec:
  parentRefs:
    - name: comppi-gateway
  hostnames:
    - "bucket.comppi.site"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: minio
          namespace: comppi-dev
          port: 9000
