apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-route
  namespace: comppi-dev
spec:
  parentRefs:
    - name: comppi-gateway
      namespace: comppi-gateway
  hostnames:
    - "api.comppi.site"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: "Access-Control-Allow-Origin"
                value: https://api.comppi.site
              - name: "Access-Control-Allow-Methods"
                value: GET, POST, PUT, DELETE, OPTIONS, PATCH, HEAD
              - name: "Access-Control-Allow-Credentials"
                value: "true"
              - name: "Access-Control-Allow-Headers"
                value: Origin, Content-Type, Accept, Authorization
      backendRefs:
        - namespace: comppi-dev
          kind: Service
          name: api-gateway
          port: 8000


---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bucket-route
  namespace: comppi-dev
spec:
  parentRefs:
    - name: comppi-gateway
      namespace: comppi-gateway
  hostnames:
    - "bucket.com-p.site"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: minio
          port: 9000

