apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.database.minio.volumeMount.nfs.path }}
    server: 172.30.1.70
