replicaCount: 1

image:
  repository: utopiandrmer/comp-nginx
  tag: latest

container:
  pullPolicy: Always
  ports:
    - containerPort: 80
    - containerPort: 443
    - containerPort: 9001

service:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30480
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
  type: NodePort