replicaCount: 1

image:
  repository: utopiandrmer/comp-nginx
  tag: latest

container:
  pullPolicy: Always
  ports:
    - containerPort: 80
    - containerPort: 443
    - containerPort: 9001

service:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 12080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 12443
    - name: minio-console
      protocol: TCP
      port: 9001
      targetPort: 21001
  type: NodePort