apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ printf "%s/%s-%s" $.Values.docker.account $.Release.Name "mysql" }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            {{- range .Values.database.mysql.ports }}
            - containerPort: {{ . }}
            {{- end }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comppi-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-vol
              mountPath: /data
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-pvc


