apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-discovery-eureka
spec:
  replicas: {{ .Values.application.auth_service.replicaCount }}
  selector:
    matchLabels:
      app: discovery-eureka
  template:
    metadata:
      labels:
        app: discovery-eureka
    spec:
      initContainers:
        - name: init-wait-for-mysql
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 mysql 3306; do echo "Waiting for MySQL..."; sleep 5; done' ]
        - name: init-wait-for-redis
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 redis 6379; do echo "Waiting for Redis..."; sleep 5; done' ]
        - name: init-wait-for-minio
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 minio 9000; do echo "Waiting for Minio..."; sleep 5; done' ]
        - name: init-wait-for-scraper
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 scraper 8080; do echo "Waiting for Scraper..."; sleep 5; done' ]

      containers:
        - name: discovery-eureka
          image: {{ .Values.application.discovery_eureka.image.name }}:{{ .Values.application.discovery_eureka.image.tag }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            - containerPort: {{ default 8080 .Values.application.discovery_eureka.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env.activeProfile }}
            - name: TZ
              value: {{ $.Values.env.timezone }}
