--- #deployment

apiVersion: apps/v1
kind: Deployment

metadata:
  name: discovery-eureka-deployment

spec:
  selector:
    matchLabels:
      app: discovery-eureka-pod

  template:
    metadata:
      name: discovery-eureka
      labels:
        app: discovery-eureka-pod

    spec:
      containers:
        - name: discovery-eureka
          image: utopiandrmer/compi-discovery-eureke


--- #service

apiVersion: v1
kind: Service

metadata:
  name: discovery-eureka-svc

spec:
  ports:
    - port: 8080

  selector:
    app: discovery-eureka-pod

  type: ClusterIP
