apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment

spec:
  selector:
    matchLabels:
      app: nginx-pod

  template:
    metadata:
      name: nginx
      labels:
        app: nginx-pod

    spec:
      containers:
        - name: nginx
          image: utopiandrmer/compi-nginx
          ports:
            - containerPort: 80
            - containerPort: 443