{{- range $key, $value := .Values.database }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      containers:
        - name: {{ $key }}
          image: {{ printf "%s/%s-%s:%s" $.Values.docker.account $.Release.Name $key $.Values.env.activeProfile }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            {{- range $value.ports }}
            - containerPort: {{ . }}
            {{- end }}
          env:
            {{- range $index, $env := $value.env }}
            - name: {{ $env.name }}
              {{- if $env.value }}
              value: {{ $env.value }}
              {{- else if $env.valueFrom }}
              valueFrom:
                {{- if $env.valueFrom.secretKeyRef }}
                secretKeyRef:
                  name: {{ $env.valueFrom.secretKeyRef.name }}
                  key: {{ $env.valueFrom.secretKeyRef.key }}
                {{- end }}
              {{- end }}
            {{- end }}
          volumeMounts:
            {{- range $value.volumeMount }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- if $value.command }}
          command:
            {{- range $val := $value.command }}
            - {{ $val }}
            {{- end }}
          {{- end }}
      volumes:
        {{- range $value.volumeMount }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s-pvc" $key .name }}
        {{- end }}
{{- end }}
