apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.application }}-pv
  labels:
    namespace: {{ .Values.env }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.volumeMount.nfs.path }}
    server: 172.30.1.70
