version: '3.8'
networks:
  comp-net:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: utopiandrmer/compi-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - api-gateway
      - discovery-eureka
      - auth-service
      - board-service

  api-gateway:
    container_name: api-gateway
    image: utopiandrmer/compi-api-gateway
    environment:
      - active_profile=dev
      - TZ=Asia/Seoul
    ports:
      - 8000:8000
    depends_on:
      - discovery-eureka

  auth-service:
    container_name: auth-service
    image: utopiandrmer/compi-auth-service
    environment:
      - active_profile=dev
      - TZ=Asia/Seoul
    ports:
      - 8081:8080
    depends_on:
      - discovery-eureka

  board-service:
    container_name: board-service
    image: utopiandrmer/compi-board-service
    environment:
      - active_profile=dev
      - TZ=Asia/Seoul
    ports:
      - 8082:8080
    depends_on:
      - discovery-eureka

  my-plant:
    container_name: my-plant
    image: utopiandrmer/compi-my-plant
    environment:
      - active_profile=dev
      - TZ=Asia/Seoul
    ports:
      - 8083:8080
    depends_on:
      - discovery-eureka

  encyclo-service:
    container_name: encyclo-service
    image: utopiandrmer/compi-encyclo-service
    environment:
      - active_profile=dev
      - TZ=Asia/Seoul
    ports:
      - 8084:8080
    depends_on:
      - discovery-eureka

  discovery-eureka:
    container_name: discovery-eureka
    image: utopiandrmer/compi-discovery-eureka
    environment:
      - active_profile=dev
      - TZ=Asia/Seoul
    ports:
      - 8761:8761
    depends_on:
      - mysql
      - redis
      - minio
      - kafka

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  scraper:
    container_name: scraper
    image: utopiandrmer/compi-scraper
    ports:
      - 8085:8080

  mysql:
    container_name: mysql
    image: utopiandrmer/compi-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=1234

  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"  # 서버 포트
      - "9001:9001"  # 콘솔 포트
    volumes:
      - "~/minio/data:/data"
    environment:
      MINIO_ROOT_USER: ADMIN
      MINIO_ROOT_PASSWORD: compcomp!!
    command: server /data --console-address ":9001"



