replicaCount: 1

image: utopiandrmer/comppi-nginx

container:
  pullPolicy: Always
  ports:
    - 80
    - 443
    - 9001

service:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30580
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30543
  type: NodePort