--- # 내부 접근
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
    - protocol: TCP
      port: 9002
      targetPort: 9002


--- # 외부 접근
apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
spec:
  selector:
    app: comppi-minio
  type: NodePort
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30901


