apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: {{ printf "%s/%s-%s" $.Values.docker.account $.Release.Name "scraper" }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            - containerPort: 8080