apiVersion: apps/v1
kind: Deployment

metadata:
  name: minio-deployment
  labels:
    app: minio

spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio

  template:
    metadata:
      labels:
        app: minio

    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio
          args:
            - server
            - /data
            - "--console-address"
            - ":9001"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              value: "ADMIN"
            - name: MINIO_ROOT_PASSWORD
              value: "compcomp!!"

          volumeMounts:
            - name: minio-storage
              mountPath: /data

      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc

---

apiVersion: v1
kind: PersistentVolume

metadata:
  name: minio-pv
  labels:
    app: minio

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" # 노드의 경로로 변경할 수 있습니다

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service

metadata:
  name: minio

spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001