apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comppi-gateway
spec:
  destination:
    name: ''
    namespace: comppi-gateway
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-charts/comppi-gateway
    repoURL: 'git@github.com:com-pi/deployment.git'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
