--- # 내부 접근
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-pod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.targetPort }}


--- # 외부 접근
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodePort
spec:
  selector:
    app: {{ .Release.Name }}-pod
  type: NodePort
  ports:
    - port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.targetPort }}
      nodePort: {{ .Values.service.nodePort }}


