apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-eureka-deployment
  namespace: {{ .Values.namespace}}
spec:
  replicas: {{ index .Values "discovery-eureka" "replicaCount" }}
  selector:
    matchLabels:
      app: discovery-eureka
  template:
    metadata:
      labels:
        app: discovery-eureka
    spec:
      initContainers:
        {{- range $key, $value := .Values.mysql}}
        - name: init-wait-for-mysql-{{ $key }}
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 {{ $key }} 3306; do echo "Waiting for MySQL..."; sleep 5; done' ]
        {{- end}}
        - name: init-wait-for-redis
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 redis 6379; do echo "Waiting for Redis..."; sleep 5; done' ]
        - name: init-wait-for-minio
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 minio 9000; do echo "Waiting for Minio..."; sleep 5; done' ]
        - name: init-wait-for-scraper
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 scraper 8080; do echo "Waiting for Scraper..."; sleep 5; done' ]

      containers:
        - name: discovery-eureka
          image: {{ index .Values "discovery-eureka" "image" "name" }}:{{ index .Values "discovery-eureka" "image" "tag" }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            - containerPort: {{ default 8080 (index .Values "discovery-eureka" "port") }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env.activeProfile }}
            - name: TZ
              value: {{ $.Values.env.timezone }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ default 8080 (index .Values "discovery-eureka" "port") }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ default 8080 (index .Values "discovery-eureka" "port") }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
