--- # 내부 접근
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
    - protocol: TCP
      port: 80
      targetPort: 80


--- # 외부 접근
apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
spec:
  selector:
    app: comppi-mysql
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30480


