apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.application }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP