apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comppi
  annotations:
    argocd-image-updater.argoproj.io/image-list: >-
      mysql=utopiandrmer/comppi-mysql,
      scraper=utopiandrmer/comppi-scraper,
      api-gateway=utopiandrmer/comppi-api-gateway,
      my-plant=utopiandrmer/comppi-my-plant,
      encyclo-service=utopiandrmer/comppi-encyclo-service,
      auth-service=utopiandrmer/comppi-auth-service,
      discovery=utopiandrmer/comppi-discovery-eureka,
      nginx=utopiandrmer/comppi-nginx
    argocd-image-updater.argoproj.io/mysql.update-strategy: newest-build
    argocd-image-updater.argoproj.io/scraper.update-strategy: newest-build
    argocd-image-updater.argoproj.io/api-gateway.update-strategy: newest-build
    argocd-image-updater.argoproj.io/my-plant.update-strategy: newest-build
    argocd-image-updater.argoproj.io/encyclo-service.update-strategy: newest-build
    argocd-image-updater.argoproj.io/auth-service.update-strategy: newest-build
    argocd-image-updater.argoproj.io/discovery-eureka.update-strategy: newest-build
    argocd-image-updater.argoproj.io/nginx.update-strategy: newest-build
spec:
  destination:
    name: ''
    namespace: comppi-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-charts/dev-test/comppi
    repoURL: 'git@github.com:com-pi/deployment.git'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
