apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-pod
  template:
    metadata:
      labels:
        app: minio-pod
    spec:
      nodeSelector:
        node-role: dev
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            {{- range .Values.service.clusterIp.ports }}
            - containerPort: {{ .port }}
            {{- end }}
          env:
            - name: MINIO_ROOT_USER
              value: "admin"
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comppi-secret
                  key: MINIO_ROOT_PASSWORD
          command: [ "minio", "server", "/data", "--console-address", ":9001" ]
          volumeMounts:
            - name: minio-vol
              mountPath: /data

      volumes:
        - name: minio-vol
          persistentVolumeClaim:
            claimName: minio-pvc


