{{ with .Values.others.nginx }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      initContainers:
        - name: init-wait-for-discovery
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 discovery-eureka 8761; do echo "Waiting for Discovery..."; sleep 5; done' ]
        - name: init-wait-for-auth-service
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 auth-service 8080; do echo "Waiting for auth service..."; sleep 5; done' ]
        - name: init-wait-for-board-service
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 board-service 8080; do echo "Waiting for board service..."; sleep 5; done' ]
        - name: init-wait-for-encyclo-service
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 encyclo-service 8080; do echo "Waiting for encyclo service..."; sleep 5; done' ]

      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          ports:
          {{- range .Values.container.ports }}
            - containerPort: {{ .containerPort }}
          {{- end }}

{{ end }}
