apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  {{ range .Values.nginx.nodePorts }}
    - name: nginx
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
      nodePort: {{ .nodePort }}
  {{ end }}
  type: NodePort