apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.releaseName }}
spec:
  selector:
    app: {{ .Values.releaseName }}-pod
  ports:
  {{ range .Values.nginx.nodePorts }}
    - name: nginx
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
      nodePort: {{ .nodePort }}
  {{ end }}
  type: NodePort