--- # 클러스터 내부
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-pod
  ports:
    {{ range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{ end }}

  type: {{ .Values.service.type }}

---  # 외부에서 콘솔 접속
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-console
spec:
  selector:
    app: {{ .Release.Name }}-pod
  ports:
    {{- range .Values.service.ports }}
      {{- if eq .name "console" }}
        name: {{ .name }}
        protocol: {{ .protocol }}
        port: {{ .port }}
        targetPort: {{ .targetPort }}
      {{- end }}
    {{- end }}

  type: LoadBalancer
  externalIPs:
    - 192.168.56.40