apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-eureka-deployment
  namespace: {{ .Values.namespace}}
spec:
  replicas: {{ .Values.containers.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application }}
  template:
    metadata:
      labels:
        app: {{ .Values.application }}
    spec:
      initContainers:
        - name: init-wait-for-redis
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 redis 6379; do echo "Waiting for Redis..."; sleep 5; done' ]
        - name: init-wait-for-minio
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 minio 9000; do echo "Waiting for Minio..."; sleep 5; done' ]
        - name: init-wait-for-scraper
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 scraper 8080; do echo "Waiting for Scraper..."; sleep 5; done' ]
        {{- if eq .Values.env "dev" }}
        - name: init-wait-for-db
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 mysql-dev 3306; do echo "Waiting for MySQL..."; sleep 5; done' ]
        {{- end }}
      containers:
        - name: discovery-eureka
          image: {{ .Values.containers.image.name }}:{{ .Values.containers.image.tag }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            - containerPort: {{ .Values.containers.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env.activeProfile }}
            - name: TZ
              value: {{ $.Values.env.timezone }}

          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.containers.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.containers.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
