apiVersion: v1
kind: Service
metadata:
  name: discovery-eureka
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: {{ .Values.application }}
  ports:
    - protocol: TCP
      port: {{ .Values.containers.port }}
      targetPort: {{ .Values.containers.port }}
  type: ClusterIP

