apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace}}

spec:
  selector:
    app: auth-service

  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}

  type: ClusterIP