apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: {{ .Values.application }}
  ports:
    - protocol: TCP
      port: {{ .Values.containers.port }}
      targetPort: {{ .Values.containers.port }}

  type: ClusterIP
