apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: {{ .Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: minio
          image: quay.io/minio/minio
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            {{- range .Values.minio.ports }}
            - containerPort: {{ . }}
            {{- end }}
          env:
            - name: MINIO_ROOT_USER
              value: "admin"
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comppi-secret
                  key: MINIO_ROOT_PASSWORD
          command: [ "minio", "server", "/data", "--console-address", ":9001" ]
          volumeMounts:
            - name: minio-vol
              mountPath: {{ .Values.minio.volumeMount.mountPath }}

      volumes:
        - name: minio-vol
          persistentVolumeClaim:
            claimName: minio-pvc


