apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-{{ .Values.env.activeProfile }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.minio.volumeMount.nfs.path }}
    server: 172.30.1.70
