--- # 내부 접근
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001


--- # 외부 접근
apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30901


