# 어플리케이션 설정
releaseName: comppi

env:
  activeProfile: dev
  timezone: Asia/Seoul

docker:
  account: utopiandrmer

application:
  api_gateway:
    image:
      name: utopiandrmer/comppi-api-gateway
      tag: latest
    replicaCount: 1
    port: 8000

  auth_service:
    image:
      name: utopiandrmer/comppi-auth-service
      tag: latest
    replicaCount: 1

  board_service:
    image:
      name: utopiandrmer/comppi-board-service
      tag: latest
    replicaCount: 1

  encyclo_service:
    image:
      name: utopiandrmer/comppi-encyclo-service
      tag: latest
    replicaCount: 1

  my_plant:
    image:
      name: utopiandrmer/comppi-my-plant
      tag: latest
    replicaCount: 1

  discovery_eureka:
    image:
      name: utopiandrmer/comppi-discovery-eureka
      tag: latest
    replicaCount: 1
    port: 8761

  scraper:
    image:
      name: utopiandrmer/comppi-scraper
      tag: latest
    replicaCount: 1


database:
  mysql:
    image:
      name: utopiandrmer/comnppi-mysql
      tag: latest
    ports:
      - 3306
    nodePorts:
      - port: 3306
        nodePort: 32306
    volumeMount:
      - name: vol1
        mountPath: "/var/lib/mysql"
        capacity: 10Gi
        nfs:
          path: /srv/nfs/kubedata/mysql
          server: 172.30.1.70

  minio:
    ports:
      - 9000
      - 9001
    nodePorts:
      - port: 9001
        nodePort: 30901

nginx:
  image:
    name: utopiandrmer/comppi-nginx
    tag: latest
  ports:
    - 443
    - 80
  nodePorts:
    - name: https
      port: 443
      nodePort: 30443
    - name: http
      port: 80
      nodePort: 30480
