releaseName: api-gateway-dev
namespace: comppi-dev
application: api-gateway

env:
  activeProfile: dev
  timezone: Asia/Seoul

containers:
  image:
    name: utopiandrmer/comppi-api-gateway
    tag: latest
  replicaCount: 1
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi