releaseName: api-gateway-dev
namespace: comppi-dev
application: api-gateway

env:
  activeProfile: dev
  timezone: Asia/Seoul

containers:
  image:
    name: utopiandrmer/comppi-api-gateway
    tag: latest
  replicaCount: 1
  port: 8000

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "250m"