namespace: comppi-dev
releaseName: discovery-eureka-prod
application: discovery-eureka

env:
  activeProfile: dev
  timezone: Asia/Seoul

containers:
  image:
    name: utopiandrmer/comppi-discovery-eureka
    tag: latest
  replicaCount: 1
  port: 8761

resources:
  requests:
    memory: "512Mi"
    cpu: "100m"
  limits:
    memory: "1Gi" # 서버 구동시 632020K 의 이상의 메모리를 요구함.
    cpu: "250m"