namespace: comppi-dev
releaseName: discovery-eureka-dev
application: discovery-eureka

env:
  activeProfile: dev
  timezone: Asia/Seoul

containers:
  image:
    name: utopiandrmer/comppi-discovery-eureka
    tag: latest
  replicaCount: 1
  port: 8761

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"