apiVersion: apps/v1
kind: Deployment
metadata:
  name: comppi-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comppi-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-vol
              mountPath: /data
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-pvc


