apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: {{ default "8080" (index .Values "api-gateway" "port") }}
      targetPort: {{ default "8080" (index .Values "api-gateway" "port") }}

  type: {{ default "ClusterIP" (index .Values "api-gateway" "serviceType") }}

