apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: {{ default "8080" .Values.api-gateway.port }}
      targetPort: {{ default "8080" .Values.api-gateway.port }}

  type: {{ default "ClusterIP" .Values.api-gateway.serviceType }}

