apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: {{ default "8080" index .Values "auth-service" "port" }}
      targetPort: {{ default "8080" index .Values "auth-service" "port" }}

  type: {{ default "ClusterIP" index .Values "auth-service" "serviceType" }}

