apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: {{ .Values.scraper.image.name }}:{{ .Values.scraper.image.tag }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            - containerPort: 8080