apiVersion: v1
kind: Service
metadata:
  name: board-service
spec:
  selector:
    app: board-service
  ports:
    - protocol: TCP
      port: {{ default "8080" .Values.board-service.port }}
      targetPort: {{ default "8080" .Values.board-service.port }}

  type: {{ default "ClusterIP" .Values.board-service.serviceType }}

