apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-plant-deployment
  namespace: {{ .Values.namespace}}
spec:
  replicas: {{ index .Values "my-plant" "replicaCount" }}
  selector:
    matchLabels:
      app: my-plant
  template:
    metadata:
      labels:
        app: my-plant
    spec:
      initContainers:
        - name: init-wait-for-discovery
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 discovery-eureka 8761; do echo "Waiting for Discovery..."; sleep 5; done' ]

      containers:
        - name: my-plant
          image: {{ index .Values "my-plant" "image" "name" }}:{{ index .Values "my-plant" "image" "tag" }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            - containerPort: {{ default 8080 (index .Values "my-plant" "port") }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env.activeProfile }}
            - name: TZ
              value: {{ $.Values.env.timezone }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ default 8080 .Values.encyclopedia.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ default 8080 .Values.encyclopedia.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3