apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image.name }}:{{ .Values.mysql.image.tag }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            {{- range .Values.mysql.ports }}
            - containerPort: {{ . }}
            {{- end }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comppi-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-vol
              mountPath: {{ .Values.mysql.volumeMount.mountPath }}
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-pvc


