{{- range $key, $value := .Values.mysql }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}-deployment
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      containers:
        - name: {{ $key }}
          image: {{ $value.image.name }}:{{ $value.image.tag }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            {{- range $value.ports }}
            - containerPort: {{ . }}
            {{- end }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comppi-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: {{ $key }}-vol
              mountPath: "/var/lib/mysql"
      volumes:
        - name: {{ $key }}-vol
          persistentVolumeClaim:
            claimName: {{ $key }}-pvc
{{- end }}
