{{- range .Values.mysql.instances }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}-pv
spec:
  capacity:
    storage: {{ .volumeMount.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .volumeMount.nfs.path }}
    server: {{ .volumeMount.nfs.server }}
{{- end }}