apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysql.volumeMount.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.mysql.volumeMount.nfs.path }}
    server: 172.30.1.70
