{{- range $key, $value := .Values.mysql }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $key }}-pv
  namespace: {{ $.Values.namespace }}
spec:
  capacity:
    storage: {{ $value.volumeMount.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ $value.volumeMount.nfs.path }}
    server: {{ $value.volumeMount.nfs.server }}
{{- end }}