{{- range $key, $value := .Values.mysql }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $key }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $value.volumeMount.capacity }}
{{- end }}