{{- range $key, $value := .Values.mysql }}
--- # 내부 접근
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
spec:
  selector:
    app: {{ $key }}
  type: ClusterIP
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
{{- end }}
# 외부 접근
{{- range $key, $value := .Values.mysql }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}-nodeport
spec:
  selector:
    app: {{ $key }}
  type: NodePort
  {{- if $value.nodePort }}
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: {{ $value.nodePort }}
  {{- end }}
{{- end }}
