--- # 내부 접근
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio-pod
  type: ClusterIP
  ports:
    {{ range .Values.service.clusterIp.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .port }}
    {{ end }}

--- # 외부 접근
apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
spec:
  selector:
    app: minio-pod
  type: NodePort
  ports:
    {{ range .Values.service.nodePort.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      nodePort: {{ .nodePort }}
    {{ end }}


