apiVersion: apps/v1
kind: Deployment
metadata:
  name: encyclo-service-deployment
spec:
  replicas: {{ index .Values "encyclo-service" "replicaCount" }}
  selector:
    matchLabels:
      app: encyclo-service
  template:
    metadata:
      labels:
        app: encyclo-service
    spec:
      initContainers:
        - name: init-wait-for-discovery
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 discovery-eureka 8761; do echo "Waiting for Discovery..."; sleep 5; done' ]

      containers:
        - name: encyclo-service
          image: {{ index .Values.encyclopedia.image.name }}:{{ index .Values.encyclopedia.image.tag }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            - containerPort: {{ default 8080 .Values.encyclopedia.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env.activeProfile }}
            - name: TZ
              value: {{ $.Values.env.timezone }}
