apiVersion: v1
kind: Service
metadata:
  name: encyclo-service
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: encyclo-service
  ports:
    - protocol: TCP
      port: {{ default "8080" .Values.encyclopedia.port }}
      targetPort: {{ default "8080" .Values.encyclopedia.port }}

  type: {{ default "ClusterIP" .Values.encyclopedia.serviceType }}

