{{- if eq .Values.env "dev" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.application }}-pvc-dev
  namespace: {{ $.Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumeMount.capacity }}
{{- end}}
