{{- if eq .Values.env "dev" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ .Values.application }}
  type: ClusterIP
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
{{- end }}
