apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: {{ .Values.pv.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/kubedata/dev/mongodb
    server: 172.30.1.70
