# 어플리케이션 설정
releaseName: comppi

env:
  activeProfile: prod
  timezone: Asia/Seoul

docker:
  account: utopiandrmer

api-gateway:
  image:
    name: utopiandrmer/comppi-api-gateway
    tag: prod-0.1.0
  replicaCount: 1
  port: 8000

auth-service:
  image:
    name: utopiandrmer/comppi-auth-service
    tag: prod-0.1.0
  replicaCount: 1

board-service:
  image:
    name: utopiandrmer/comppi-board-service
    tag: prod-0.1.0
  replicaCount: 1

encyclo-service:
  image:
    name: utopiandrmer/comppi-encyclo-service
    tag: prod-0.1.0
  replicaCount: 1

my-plant:
  image:
    name: utopiandrmer/comppi-my-plant
    tag: prod-0.1.0
  replicaCount: 1

discovery-eureka:
  image:
    name: utopiandrmer/comppi-discovery-eureka
    tag: prod-0.1.0
  replicaCount: 1
  port: 8761

scraper:
  image:
    name: utopiandrmer/comppi-scraper
    tag: prod-0.1.0
  replicaCount: 1

mysql:
  mysql-auth:
    image:
      name: utopiandrmer/comppi-mysql-auth
      tag: prod-0.1.0
    ports:
      - 3306
    nodePorts: 32307
    volumeMount:
      capacity: 10Gi
      nfs:
        path: /srv/nfs/kubedata/prod/mysql-auth
        server: 172.30.1.70

  mysql-board:
    image:
      name: utopiandrmer/comppi-mysql-board
      tag: prod-0.1.0
    ports:
      - 3306
    nodePorts: 32308
    volumeMount:
      capacity: 10Gi
      nfs:
        path: /srv/nfs/kubedata/prod/mysql-board
        server: 172.30.1.70

  mysql-plant:
    image:
      name: utopiandrmer/comppi-mysql-plant
      tag: prod-0.1.0
    ports:
      - 3306
    nodePorts: 32309
    volumeMount:
      capacity: 10Gi
      nfs:
        path: /srv/nfs/kubedata/prod/mysql-plant
        server: 172.30.1.70

  mysql-encyclopedia:
    image:
      name: utopiandrmer/comppi-mysql-encyclopedia
      tag: prod-0.1.0
    ports:
      - 3306
    nodePort: 32310
    volumeMount:
      capacity: 10Gi
      nfs:
        path: /srv/nfs/kubedata/prod/mysql-encyclopedia
        server: 172.30.1.70

minio:
  ports:
    - 9000
    - 9001
  nodePorts:
    - port: 9001
      nodePort: 30901
  volumeMount:
    mountPath: "/data"
    capacity: 20Gi
    nfs:
      path: /srv/nfs/kubedata/prod/minio
      server: 172.30.1.70

nginx:
  image:
    name: utopiandrmer/comppi-nginx
    tag: prod-0.1.0
  ports:
    - 443
    - 80
  nodePorts:
    - name: https
      port: 443
      nodePort: 30443
    - name: http
      port: 80
      nodePort: 30480
