replicaCount: 1

image:
  repository: utopiandrmer/comp-my-plant
  tag: latest

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP

env:
  activeProfile: dev
  timezone: Asia/Seoul
