apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comppi
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
    {{ range .Values.images }}
      {{- . | nindent 6}}=utopiandrmer/comppi-{{ . }}:^dev-\d{8}-\d{4}$
    {{ end }}
    {{ range .Values.images }}
    argocd-image-updater.argoproj.io/{{ . }}.allow-tags: 'regexp:^dev-\d{8}-\d{6}$'
    argocd-image-updater.argoproj.io/{{ . }}.update-strategy: name
    {{ end }}
spec:
  destination:
    name: ''
    namespace: comppi-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-chart/comppi
    repoURL: 'git@github.com:com-pi/deployment.git'
    targetRevision: main
    helm:
      valueFiles:
        - values-dev.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
