replicaCount: 3

zookeeper:
  enabled: true
  replicaCount: 3

kafka:
  enabled: true
  replicaCount: 3
  configurationOverrides:
    "auto.create.topics.enable": "true"
    "zookeeper.connect": "my-zookeeper:2181"

controller:
  replicaCount: 0  # Zookeeper 모드에서는 컨트롤러 노드를 사용하지 않습니다.

service:
  type: ClusterIP  # LoadBalancer 대신 ClusterIP 사용

externalAccess:
  enabled: false  # 외부 접근 비활성화

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 1Gi
    cpu: 1
