replicaCount: 3

zookeeper:
  enabled: true
  replicaCount: 3

service:
  type: ClusterIP  # LoadBalancer 대신 ClusterIP 사용
  port: 9092
  headless:
    enabled: true  # Headless 서비스 설정

externalAccess:
  enabled: false  # 외부 접근 비활성화

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 1Gi
    cpu: 1
