replicaCount: 1

image:
  repository: utopiandrmer/comp-mysql
  tag: latest

service:
  type: ClusterIP
  port: 3306
  targetPort: 3306
  protocol: TCP

env:
  activeProfile: dev
  timezone: Asia/Seoul

pv:
  capacity: 5Gi
  node:
    - "node1.comp"
    -

secret:
  rootPasswordSecretName: comp-secret
  rootPasswordSecretKey: MYSQL_ROOT_PASSWORD
