apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scraper
spec:
  replicas: {{ .Values.application.scraper }}
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: {{ .Values.application.scraper.image.name }}:{{ .Values.application.api_gateway.image.tag }}
          imagePullPolicy: {{ if eq $.Values.env.activeProfile "dev" }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            - containerPort: 8080